
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandChief
  name: job-name-centcommchief
  description: job-description-centcommchief
  playTimeTracker: JobCentralCommandChief
  setPreference: false
  weight: 150
  startingGear: CentcomChiefGear
  icon: "JobIconCentCommChief"
  supervisors: job-supervisors-centcomchieft 
  whitelisted: true
  canBeAntag: false
  skills:
  - All
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  accessGroups:
  - AllAccess
  access:
  - CentralCommandChief
  - CentralCommand
  - CentralCommandOperator
  - CentralCommandWorker
  - CentralCommandOSO
  - CentralCommandCommand
  - CentralCommandDSO
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, NutrimentPumpImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomChiefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAdmiral
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCentcomNaval
    back: ClothingBackpackDuffelHolding
    outerClothing: ClothingOuterArmorCentcomCarapace
    neck: ClothingNeckCloakCentcom
    id: CentcomChiefPDA
    ears: ClothingHeadsetAltCentComChief
    pocket1: BoxFolderCentCom 
    pocket2: WeaponPulsePistol
    underwearb: ADTClothingUnderwearBottomBoxersWhite
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - EmergencyNitrogenTankFilled
    - TelescopicBaton
    - WeaponDisablerAdvanced
    - ExecutiveIDCard
    - RubberStampCentcom
    - RubberStampApproved
    - RubberStampDenied