
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandChief
  name: job-name-centcommchief
  description: job-description-centcommchief
  playTimeTracker: JobCentralCommandChief
  setPreference: false
  weight: 100
  startingGear: CentcomChiefGear
  icon: "JobIconCentCommChief"
  supervisors: job-supervisors-centcomchieft 
  whitelisted: true
  canBeAntag: false
  skills:
  - All
  requirements:
  - !type:AgeRequirement
    requiredAge: 20
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, RadioImplantCentcomm, NutrimentPumpImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomChiefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAdmiral
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCentcomNaval
    back: ClothingBackpackDuffelHolding
    outerClothing: ClothingOuterArmorCentcomCarapace
    neck: ClothingNeckCloakCentcom
    id: CentcomChiefPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: BoxFolderCentCom 
    pocket2: WeaponPulsePistol
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - EmergencyNitrogenTankFilled
    - TelescopicBaton
    - ExecutiveIDCard
    - RubberStampCentcom
    - RubberStampApproved
    - RubberStampDenied