
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandOperator
  name: job-name-centcommoperator
  description: job-description-centcommoperator
  playTimeTracker: JobCentralCommandOperator
  setPreference: true
  weight: 100
  startingGear: CentcomOperatorGear
  icon: "JobIconCentCommOperator"
  supervisors: job-supervisors-centcom
  whitelisted: true
  canBeAntag: false
  skills:
  - All
  requirements:
  - !type:AgeRequirement
    requiredAge: 20
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - CentralCommandOperator
  - CentralCommandDSO
  - CentralCommandCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, NutrimentPumpImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomOperatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    back: ClothingBackpackSatchelLeather
    id: CentcomOperatorPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: BoxFolderCentCom
    pocket2: WeaponDisablerAdvanced
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - BoxFolderCentComClipboard
    - EmergencyNitrogenTankFilled
    - TelescopicBaton