
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandOSO
  name: job-name-centcommoso
  description: job-description-centcommoso
  playTimeTracker: JobCentralCommandOSO
  setPreference: false
  weight: 100
  startingGear: CentcomOSOGear
  icon: "JobIconCentCommOSO"
  supervisors: job-supervisors-centcomchieft 
  whitelisted: true
  canBeAntag: false
  skills:
  - All
  requirements:
  - !type:AgeRequirement
    requiredAge: 20
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - CentralCommandDSO
  - CentralCommandOSO
  - CentralCommandCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, NutrimentPumpImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomOSOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficerBlack
    shoes: ClothingShoesCentcomBlack
    head: ClothingHeadCapCentcomBlack
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackDuffelHolding
    outerClothing: ClothingOuterArmorHeavy
    neck: ClothingNeckCloakCentcomBlack
    id: SpecialOperationsOfficerPDA
    ears: ClothingHeadsetAltCentComChief
    pocket1: BoxFolderCentCom 
    pocket2: WeaponPulsePistol
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - EmergencyNitrogenTankFilled
    - TelescopicBaton
    - WeaponDisablerAdvanced
    - ExecutiveIDCard
    - RubberStampApproved
    - RubberStampDenied