
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandOSO
  name: job-name-centcommoso
  description: job-description-centcommoso
  playTimeTracker: JobCentralCommandOSO
  setPreference: false
  weight: 100
  startingGear: CentcomOSOGear
  icon: "JobIconCentCommOSO"
  supervisors: job-supervisors-centcomchieft 
  whitelisted: true
  canBeAntag: false
  skills:
  - All
  requirements:
  - !type:AgeRequirement
    requiredAge: 20
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - CentralCommandDSO
  - CentralCommandOSO
  - CentralCommandCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant]

- type: startingGear
  id: CentcomOSOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficerBlack
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadCapCentcomBlack
    eyes: ClothingEyesGlassesDeathsquad
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackDuffelHolding
    outerClothing: ClothingOuterArmourInvisible
    neck: ExecutiveIDCard
    id: SpecialOperationsOfficerPDA
    ears: ClothingHeadsetAltCentComOSO
    pocket1: WeaponRevolverMateba 
    pocket2: WeaponPulsePistol
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - EmergencyNitrogenTankFilled
    - TelescopicBaton
    - WeaponDisablerAdvanced
    - ClothingNeckCloakCentcomBlack
    - NukeOverride
    - RubberStampApproved
    - RubberStampDenied
    - CentralCommandBusinessCard
    - CentralCommandBusinessCard
    - DeterrentCaseFilled