- type: job
  id: CentCommServiceWorker
  name: job-name-centcommserviceworker
  description: job-description-centcommserviceworker
  playTimeTracker: JobCentCommServiceWorker
  startingGear: CentCommServiceWorkerGear
  weight: 100
  whitelisted: true
  setPreference: true
  canBeAntag: false
  icon: "JobIconCentCommServiceWorker"
  supervisors: job-supervisors-centcomservice
  requirements:
  - !type:AgeRequirement
    requiredAge: 18
  access:
  - CentralCommand
  - CentralCommandWorker
  - Service
  - Maintenance
  - Bar
  - Kitchen
  - Hydroponics
  - Janitor
  - Cargo
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CentCommServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CentcomServiceWorkerPDA
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitMilitaryService
    back: ClothingBackpackDuffel
    underwearb: ADTClothingUnderwearBottomBoxersWhite
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - ClothingUniformJumpsuitBartender
    - ClothingUniformJumpskirtBartender
    - EmergencyNitrogenTankFilled