- type: department
  id: LiveCentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandChief
  - CentralCommandOfficial
  - CentralCommandOperator
  - CentCommServiceWorker
  editorHidden: false
  weight: 120
