- type: playTimeTracker
  id: JobCentCommServiceWorker

- type: playTimeTracker
  id: JobCentralCommandOperator

- type: playTimeTracker
  id: JobCentralCommandChief

- type: playTimeTracker
  id: JobCentralCommandOSO